############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

#[[main]]
#name = "Elements"
#url = "/elements"
#weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "Your Swing"
url = "/"
weight = 4

[[main]]
parent = "Your Swing"
name = "Pitching"
url = "/pitching"

[[main]]
parent = "Your Swing"
name = "Driving"
url = "/driving"

[[main]]
parent = "Your Swing"
name = "Chipping"
url = "/chipping"

[[main]]
parent = "Your Swing"
name = "Putting"
url = "/putting"

[[main]]
parent = "Blog"
name = "Blog Posts"
url = "/blog"

[[main]]
parent = "About"
name = "Contact"
url = "/contact"

[[main]]
parent = "About"
name = "Authors"
url = "/authors"

[[main]]
parent = "Blog"
name = "Categories"
url = "/categories"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3










