############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Elements"
url = "/elements"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
weight = 5
name = "your swing"

[[main]]
parent = "your swing"
name = "pitching"
url = "/pitching"

[[main]]
parent = "your swing"
name = "driving"
url = "/driving"

[[main]]
parent = "your swing"
name = "chipping"
url = "/chipping"

[[main]]
parent = "your swing"
name = "putting"
url = "/putting"

[[main]]
parent = "Pages"
name = "Blog"
url = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
url = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3



